output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/experiments/

dataset:
  class: FB15k-237
  root: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  randomized_edge_drop: 0.05
  use_pyg_propagation: yes

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 32
  num_epoch: 0
  log_interval: 100

checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/fb15k237_005b.pth