output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/explanation/
# output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/experiments/

dataset:
  class: WN18RR
  root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/WN18RR/
  # root: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/WN18RR/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: RelPGExplainer

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  num_beam: 5
  path_topk: 5
  # get_path: True

explainer:
  class: RelPGExplainer
  reg_coefs: [0.03, 0.05]
  temp: [5.0, 1.0]
  sample_bias: 0.0
  rel_emb: yes
  num_mlp_layer: 3
  mask_type: hard_node_mask
  max_num_nodes_in_mask: 1000
  return_detailed_loss: yes

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@50, hits@100, inclusion]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 4
  num_epoch: 5
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/wn18rr_transductive_best.pth
# checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/WN18RR_transductive_best.pth