output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/explanation/
# output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/explanation/

dataset:
  class: WN18RR
  root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/WN18RR/
  # root: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/WN18RR/
  # combined_graph: yes

wandb:
  use: {{ use_wandb }}
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: RelPGExplainer-FixedPipeline

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  num_beam: 5
  path_topk: 5
  use_pyg_propagation: yes
  # get_path: True

explainer:
  class: RelPGExplainer
  size_reg: 1
  ent_reg: 3
  temp_start: 4
  temp_end: 3
  sample_bias: 0.5
  rel_emb: yes
  num_mlp_layer: 4
  use_default_aggr: no
  topk_tails: 3

explainer_eval: # the evaluation of the explainers
  # eval_mask_type: hard_edge_mask_top_ratio
  eval_mask_type: hard_node_mask_top_k
  hard_edge_mask_threshold: 0.5
  hard_node_mask_top_k: [100]
  # hard_edge_mask_top_ratio: [0.001,0.01,0.1,0.3]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@50, hits@100, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 1.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: 0
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/wn18rr_02b.pth
explainer_checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/wn18rr_best_kg_sampler.pth
save_explanation: yes
evaluate_on_train: yes