# output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/experiments/
output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/experiments/

dataset:
  class: WN18RR
  # root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/WN18RR/
  root: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{ use_wandb }}
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: NBFNet-ego-0.5b

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  randomized_edge_drop: 0.5
  use_pyg_propagation: yes

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 16
  num_epoch: 20
  log_interval: 100