output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/explanation/EdgeRandomWalk/

dataset:
  class: FB15k-237
  root:  /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-FB15k-237
  name: EdgeRandomWalk-InvertEdge-IgnoreHead

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  use_pyg_propagation: yes

explainer:
  class: RandomWalk
  teleport_prob: 0.15
  edge_random_walk: yes
  convergence: edge
  invert_edges: yes
  ignore_head: yes
  topk_tails: 3
  use_teleport_adj: no
  ego_network: yes
  factual: yes
  counter_factual: no

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [25, 50, 75, 100, 300, 500]
  eval_type: [factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{gpus}}
  batch_size: 4
  num_epoch: 0
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_dist_eval.pth
eval_checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_dist_eval.pth

save_explanation: yes
valid_walltime: 20