output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/explanation/PGExplainer/

dataset:
  class: FB15k-237
  root:  /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-FB15k-237
  name: PGExplainer-Jubail

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  use_pyg_propagation: yes

explainer:
  class: PGExplainer
  size_reg: 5
  ent_reg: 3
  temp_start: 2
  temp_end: 2
  sample_bias: 0.5
  num_mlp_layer: 2
  topk_tails: 1
  ego_network: yes
  use_default_aggr: no
  mode: inductive
  factual: yes
  counter_factual: no

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [10, 50, 100, 300, 500, 1000]
  eval_type: [factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 1.0e-4

train:
  gpus: {{gpus}}
  batch_size: 4
  num_epoch: 10
  log_interval: 100
  num_workers: 4
  step: 1
  checkpoint_best: yes
  train_on_val: yes

checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_dist_eval.pth
eval_checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_dist_eval.pth

save_explanation: yes
evaluate_on_train: yes
train_walltime: 20
valid_walltime: 10