output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/Hetero/

dataset:
  class: aug_citation
  root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/

wandb:
  use: {{ use_wandb }}
  entity: "team_ryoji"
  project: SampleX-AugCitation
  name: NBFNet

model:
  class: NBFNet
  input_dim: 16
  hidden_dims: [16, 16, 16]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  randomized_edge_drop: 0.0
  use_pyg_propagation: yes
  remove_ground_truth: yes

task:
  sample_neg_edges: yes
  metric: [auroc]

eval:
  randomized_edge_drop: [0, 0.2, 0.4, 0.6, 0.8, 1]
  eval_on_edge_drop: no
  remove_ground_truth: no
  keep_ground_truth: no

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 8
  num_epoch: 10
  log_interval: 100