output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/Hetero/

dataset:
  class: aug_citation
  root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/

wandb:
  use: {{ use_wandb }}
  entity: "team_ryoji"
  project: SampleX-AugCitation
  name: NBFNet

model:
  class: NBFNet
  input_dim: 16
  hidden_dims: [16, 16, 16]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  randomized_edge_drop: 0.0
  use_pyg_propagation: yes

task:
  sample_neg_edges: yes
  metric: [auroc]

# task:
#   num_negative: 32
#   strict_negative: yes
#   adversarial_temperature: 0.5
#   metric: [mr, mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: {{ gpus }}
  batch_size: 8
  num_epoch: 10
  log_interval: 100