# output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/Hetero/
output_dir: /scratch/oge208/Graph-Transformer/NBFNet-PyG/RWExplainer/

dataset:
  class: synthetic
  # root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/
  root: /scratch/oge208/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-UserItemAttr
  name: RWExplainer-NoNeg-CounterFactual-Ola

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  randomized_edge_drop: 0.0
  use_pyg_propagation: yes

explainer:
  class: RelPGExplainer
  size_reg: 1
  ent_reg: 3
  temp_start: 4
  temp_end: 3
  sample_bias: 0.5
  rel_emb: yes
  num_mlp_layer: 4
  use_default_aggr: no
  topk_tails: 3
  random_walk_loss: yes
  adj_aggr: sum
  teleport_prob: 0.2
  rw_topk_node: 100
  reg_loss_inside: 1
  reg_loss_outside: 1
  ego_network: no
  counter_factual: yes

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_threshold: 0.5
  hard_edge_mask_top_k: [10, 30, 60, 100]

task:
  num_negative: 0
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, hits@50, hits@100, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-4

train:
  gpus: [0]
  batch_size: 32
  num_epoch: 100
  log_interval: 100
  num_workers: 4
  step: 1

# checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/synthetic-nbfnet-hits.pth
checkpoint: /scratch/oge208/Graph-Transformer/NBFNet-PyG/checkpoint/synthetic-nbfnet-hits.pth