output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/Hetero/
# output_dir: /scratch/oge208/Graph-Transformer/NBFNet-PyG/Hetero/

dataset:
  class: synthetic
  root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/
  # root: /scratch/oge208/Graph-Transformer/NBFNet-PyG/datasets/hetero_dataset/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-UserItemAttr
  name: RGCN-NoNodeEmb-Colab

model:
  class: RGCN
  input_dim: 128
  hidden_dims: [128, 128]
  randomized_edge_drop: 0.0
  use_node_emb: no
  random_node_features: normal
  aggr: sum

task:
  sample_neg_edges: no
  metric: [auroc]

optimizer:
  class: Adam
  lr: 1.0e-3

train:
  gpus: [1]
  batch_size: 16
  num_epoch: 100
  log_interval: 100
  step: 1