output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/explanation/RAWExplainer/

dataset:
  class: FB15k-237
  root:  /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-FB15k-237
  name: RAWExplainer

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  use_pyg_propagation: yes

explainer:
  class: RelPGExplainer
  size_reg: 2
  ent_reg: 3
  temp_start: 5
  temp_end: 4
  sample_bias: 0.5
  rel_emb: yes
  num_mlp_layer: 2
  use_default_aggr: no
  topk_tails: 3
  ego_network: yes
  # Random Walks
  random_walk_loss: yes
  adj_aggr: sum
  teleport_prob: 0.15
  rw_topk_node: 500
  reg_loss_inside: 0.5
  reg_loss_outside: 0
  use_teleport_adj: no
  max_power_iter: -1
  # Optims
  factual: yes
  counter_factual: yes
  expl_gnn_model: yes

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000, 5000]
  eval_type: [factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-5

train:
  gpus: {{gpus}}
  batch_size: 4
  num_epoch: 0
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_015b.pth
eval_checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_015b.pth
explainer_checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/fb15k237_explainers/rawexplainer.pth

save_explanation: yes
evaluate_on_train: yes
