# output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/GNNExplainer/
output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/explanation/GNNExplainer/

dataset:
  class: WN18RR
  # root: /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/
  root:  /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: GNNExplainer-Jubail

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  use_pyg_propagation: yes

explainer:
  class: GNNExplainer
  size_reg: 1
  ent_reg: 3
  topk_tails: 2
  ego_network: no
  use_default_aggr: no
  factual: yes
  counter_factual: no

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000]
  eval_type: [factual_eval, counter_factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-4

train:
  gpus: [0,1]
  batch_size: 16
  num_epoch: 10
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_0b.pth
eval_checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
