output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/explanation/PowerLink/

dataset:
  class: WN18RR
  root:  /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: PowerLink

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  use_pyg_propagation: yes

explainer:
  class: PowerLink
  prune_graph: yes
  with_path_loss: yes
  timeout_duration: 3
  topk_tails: 1
  k_core: 2
  num_mlp_layer: 2
  adj_aggr: max
  max_path_length: 3
  size_reg: 2
  ego_network: yes
  use_default_aggr: no
  factual: yes
  counter_factual: no

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000]
  eval_type: [factual_eval, counter_factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 0.01

train:
  gpus: {{gpus}}
  batch_size: 4
  num_epoch: 4
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_0b.pth
eval_checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth