output_dir: /storage/ryoji/Graph-Transformer/NBFNet-PyG/explanation/XGExplainer/

dataset:
  class: WN18RR
  root:  /storage/ryoji/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: XGExplainer

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  use_pyg_propagation: yes

explainer:
  class: PGExplainer
  size_reg: 2
  ent_reg: 5
  temp_start: 5
  temp_end: 4
  sample_bias: 0.1
  num_mlp_layer: 4
  topk_tails: 1
  ego_network: no
  use_default_aggr: no
  mode: inductive
  factual: yes
  counter_factual: no
  
explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000, 5000]
  eval_type: [factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 0.005

train:
  gpus: {{gpus}}
  batch_size: 8
  num_epoch: 0
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
eval_checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
explainer_checkpoint: /storage/ryoji/Graph-Transformer/NBFNet-PyG/checkpoint/wn18rr_explainers/xgexplainer.pth

save_explanation: yes
evaluate_on_train: yes