output_dir: /scratch/dd115/Graph-Transformer/NBFNet-PyG/explanation/RAWExplainer1/

dataset:
  class: WN18RR
  root:  /scratch/dd115/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: RAWExplainer-DD#1

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  use_pyg_propagation: yes

explainer:
  class: RelPGExplainer
  size_reg: 1
  ent_reg: 3
  temp_start: 4
  temp_end: 3
  sample_bias: 0.5
  rel_emb: yes
  num_mlp_layer: 4
  use_default_aggr: no
  topk_tails: 3
  ego_network: no
  # Random Walks
  random_walk_loss: yes
  adj_aggr: sum
  teleport_prob: 0.2
  rw_topk_node: 100
  reg_loss_inside: 1
  reg_loss_outside: 1
  use_teleport_adj: yes
  # Optims
  factual: yes
  counter_factual: yes
  expl_gnn_model: yes

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000]
  eval_type: [factual_eval, counter_factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-4

train:
  gpus: [0,1]
  batch_size: 8
  num_epoch: 10
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /scratch/dd115/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
eval_checkpoint: /scratch/dd115/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
