output_dir: /scratch/dd115/Graph-Transformer/NBFNet-PyG/explanation/RAWExplainer/

dataset:
  class: WN18RR
  root:  /scratch/dd115/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: {{use_wandb}}
  entity: "team_ryoji"
  project: SampleX-WN18RR
  name: RAWExplainer-Ablation-Factual

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: no
  use_pyg_propagation: yes

explainer:
  class: RelPGExplainer
  size_reg: 4
  ent_reg: 1
  temp_start: 1
  temp_end: 1
  sample_bias: 0.3
  rel_emb: yes
  num_mlp_layer: 2
  use_default_aggr: no
  topk_tails: 2
  ego_network: yes
  joint_training: no
  # Random Walks
  random_walk_loss: yes
  adj_aggr: sum
  teleport_prob: 0.2
  rw_topk_node: 50
  reg_loss_inside: 0.5
  reg_loss_outside: 0.5
  use_teleport_adj: yes
  # Optims
  factual: yes
  counter_factual: no
  expl_gnn_model: yes

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000, 5000]
  eval_type: [factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 1
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-4

train:
  gpus: {{gpus}}
  batch_size: 8
  num_epoch: 0
  log_interval: 100
  num_workers: 4
  step: 1
  checkpoint_best: yes

checkpoint: /scratch/dd115/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
eval_checkpoint: /scratch/dd115/Graph-Transformer/NBFNet-PyG/checkpoint/explain/wn18rr_015b.pth
explainer_checkpoint: /scratch/dd115/Graph-Transformer/NBFNet-PyG/checkpoint/wn18rr_explainers/rawexp-ablation-f.pth

save_explanation: yes
evaluate_on_train: yes