output_dir: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/explanation/PaGELink/

dataset:
  class: FB15k-237
  root:  /scratch/rk3570/Graph-Transformer/NBFNet-PyG/datasets/knowledge_graphs/

wandb:
  use: yes
  entity: "team_ryoji"
  project: SampleX-FB15k-237
  name: PaGELink-Jubail

model:
  class: NBFNet
  input_dim: 32
  hidden_dims: [32, 32, 32, 32, 32, 32]
  message_func: distmult
  aggregate_func: pna
  short_cut: yes
  layer_norm: yes
  dependent: yes
  remove_one_hop: yes
  use_pyg_propagation: yes

explainer:
  class: PaGELink
  prune_graph: yes
  with_path_loss: yes
  timeout_duration: 3
  topk_tails: 1
  prune_max_degree: 50
  k_core: 2
  num_paths: 20
  alpha: 1
  beta: 1
  ego_network: yes
  use_default_aggr: no
  factual: yes
  counter_factual: no

explainer_eval: # the evaluation of the explainers
  eval_mask_type: hard_edge_mask_top_k
  hard_edge_mask_top_k: [100, 300, 500, 1000]
  eval_type: [factual_eval, counter_factual_eval]

task:
  num_negative: 32
  strict_negative: yes
  adversarial_temperature: 0.5
  metric: [mr, mrr, hits@1, hits@3, hits@10, inclusion, num_edges, num_nodes]

optimizer:
  class: Adam
  lr: 5.0e-3

train:
  gpus: [0]
  batch_size: 8
  num_epoch: 10
  log_interval: 100
  num_workers: 4
  step: 1

checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_0b.pth
eval_checkpoint: /scratch/rk3570/Graph-Transformer/NBFNet-PyG/checkpoint/explain/fb15k237_015b.pth
